import * as core from '@actions/core';
import * as github from '@actions/github';
import OpenAI from 'openai';

async function run ()
{
  try
  {
    const openaiApiKey = process.env.OPENAI_API_KEY;
    const githubToken = process.env.GITHUB_TOKEN;

    if (!openaiApiKey)
    {
      throw new Error('OPENAI_API_KEY environment variable is not set.');
    }
    if (!githubToken)
    {
      throw new Error('GITHUB_TOKEN environment variable is not set.');
    }

    const octokit = github.getOctokit(githubToken);
    const openai = new OpenAI({ apiKey: openaiApiKey });

    const { owner, repo, number: pull_number } = github.context.issue;

    if (!pull_number)
    {
      throw new Error('This action was not triggered by a pull_request event.');
    }

    const { data: prDiff } = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number,
      mediaType: {
        format: 'diff'
      }
    });

    const prompt = `
The following is a Git diff of changes in this Pull Request compared to the "main" branch.
Generate concise, helpful README-style documentation describing what changed and why.

Diff:
${prDiff}
`;

    console.log('Calling OpenAI API to generate documentation...');
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: 'You are a helpful documentation generator that creates nicely formatted README.md content.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_tokens: 800
    });

    const docs = response.choices?.[0]?.message?.content?.trim() || '';
    if (!docs)
    {
      throw new Error('No documentation was generated by the OpenAI API.');
    }

    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: pull_number,
      body: `## 📝 Auto-Generated Documentation\n\n${docs}`
    });

    console.log('Successfully posted documentation as a PR comment.');

  } catch (error)
  {
    console.error('Error generating or posting documentation:', error);
    core.setFailed(error.message);
  }
}

run();
