- name: Generate Documentation
  run: |
    COMMIT_COUNT=$(git rev-list --count HEAD)
    if [ "$COMMIT_COUNT" -lt 2 ]; then
      echo "Only one (or zero) commits in the repository—skipping diff."
      exit 0
    fi

    DIFF=$(git diff HEAD^ HEAD)
    if [ -z "$DIFF" ]; then
      echo "No changes detected."
      exit 0
    fi

    RESPONSE=$(python3 - <<EOF
import os
import openai

openai.api_key = os.getenv("OPENAI_API_KEY")

diff_text = """${DIFF}"""

response = openai.ChatCompletion.create(
    model="gpt-4",
    messages=[
        {"role": "system", "content": "You are a documentation assistant."},
        {"role": "user", "content": f"Generate a changelog entry for the following Git diff:\n{diff_text}"}
    ]
)

print(response['choices'][0]['message']['content'])
EOF
    )

    echo -e "\n## Changes in this commit\n$RESPONSE" >> CHANGELOG.md
    git add CHANGELOG.md
