name: Generate Changelog Entry

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install OpenAI
        run: |
          pip install --upgrade pip
          pip install openai==1.0.0

      - name: Generate changelog entry
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DIFF: ${{ github.event.head_commit.message }}
        run: |
          RESPONSE=$(python <<'EOF'
          import openai
          import os

          client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

          response = client.chat.completions.create(
              model="gpt-3.5-turbo",
              messages=[
                  {"role": "system", "content": "You are a documentation assistant."},
                  {"role": "user", "content": f"Generate a changelog entry for the following Git diff:\n{os.getenv('DIFF', '')}"}
              ]
          )

          print(response.choices[0].message.content)
          EOF
          )
          echo -e "\n## Changes in this commit\n$RESPONSE" >> CHANGELOG.md
          git add CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update changelog"
          git push
