name: Generate Changelog Entry

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install OpenAI (1.0.0 or later)
        run: |
          pip install --upgrade pip
          pip install openai

      - name: Generate changelog entry
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # For demonstration, we’re using the commit message as "DIFF". 
          # You can replace this with a real diff if you prefer (see below).
          DIFF: ${{ github.event.head_commit.message }}
        run: |
          RESPONSE=$(python <<'EOF'
          import os
          import openai

          openai.api_key = os.getenv("OPENAI_API_KEY")

          # Get the commit message or any other "diff" text
          diff_text = os.getenv("DIFF", "")

          # Using the new openai.chat.completions interface (openai>=1.0.0)
          response = openai.chat.completions.create(
              model="gpt-4",  # or "gpt-3.5-turbo" if desired
              messages=[
                  {"role": "system", "content": "You are a documentation assistant."},
                  {"role": "user", "content": f"Generate a changelog entry for the following Git diff:\n{diff_text}"}
              ]
          )

          # Print out just the AI-generated content
          print(response.choices[0].message.content)
          EOF
          )
          echo -e "\n## Changes in this commit\n$RESPONSE" >> CHANGELOG.md
          git add CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update changelog"
          git push
